#!/usr/bin/bash

# Processes to wait for before exiting the script
pids=()

# Install ansible
echo "Installing ansible..."
sudo apt-get update
sudo apt-get install -y software-properties-common ca-certificates ansible &
pids+=($!)

# Clone the repo with ansible configs
git clone https://github.com/aalbaali/workstation_setup.git /tmp/workstation_setup --depth 1 &
pids+=($!)


echo "Cloning workstation setup repo..."
# Wait for all processes to finish
for pid in "${pids[@]}"; do
  wait "$pid"
done

# Run ansible playbook
echo "Running ansible playbook..."
cd /tmp/workstation_setup/ansible
ansible-playbook tasks/install_minimum_packages.yaml
ansible-playbook tasks/setup_zsh.yaml
ansible-playbook tasks/setup_nvim.yaml
ansible-playbook tasks/setup_vim.yaml
