require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.bufferline"
require "user.lualine"
require "user.toggleterm"
-- require "user.project"
require "user.impatient"
require "user.indentline"
-- require "user.alpha"
require "user.whichkey"
require "user.autocommands"

-- From old config
require "user.fzf"
require "user.cmake"
require "user.asyncrun"
require "user.clangformat"
require "user.cmake"
require "user.diffview"
require "user.doxygentoolkit"
require "user.fugitive"
require "user.headerguard"
require "user.nerdcommenter"
require "user.startify"
require "user.undotree"
