- name: Install nvm
  ansible.builtin.shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: Check current node version
  shell: ". ~/.nvm/nvm.sh && nvm current | sed 's/\\..*//' 2>/dev/null"
  register: node_version

- name: Install and use Node.js 16
  shell: ". ~/.nvm/nvm.sh && nvm install 16 && nvm alias default 16"
  when: node_version.stdout != "v16"
